Added POC launchers for RA and BootMenu (BootMenu doesn't work it's WIP)

diff --git a/bleemsync/etc/bleemsync/SUP/scripts/intercept b/bleemsync/etc/bleemsync/SUP/scripts/intercept
--- a/bleemsync/etc/bleemsync/SUP/scripts/intercept
+++ b/bleemsync/etc/bleemsync/SUP/scripts/intercept
@@ -20,15 +20,6 @@
 # ModMyClassic.com / https://discordapp.com/invite/8gygsrw
 ###############################################################################
 
-### CHECK FOR LAUNCH SCRIPT ###################################################
-# If launch script exists run it instead of pcsx/RA
-if [ -f "/data/AppData/sony/title/launch.sh" ]; then
-  echo "[INTERCEPT](INFO) launch.sh exists"
-  exec "/data/AppData/sony/title/launch.sh" 
-  # Shouldn't get to here
-  exit 1
-fi
-
 start=$(date +%s%N)
 ### LOAD CONFIGURATION ########################################################
 source "/var/volatile/bleemsync.cfg"
@@ -86,7 +77,7 @@ resume_ui_menu() {
 ### START INTERCEPT SCRIPT ####################################################
 # This should be launched directly from ui_menu by
 # substituing the sPcsxExecPath in /usr/sony/share/data/preferences/system.pre
-# with the path to this script
+# with the path to this script if not intercepted by launch.sh
 ###############################################################################
 echo "[INTERCEPT](INFO) Starting PS Classic Intercept"
 if [ "$#" -ge 1 ]; then
@@ -104,108 +95,112 @@ killall -s TERM auto_dimmer &> /dev/null
 intercept_command=""
 found_cdfile=false
 
-# Loop through each argument to pull out information relating to which game is being loaded
-# and whether this is a Save State load
-start_arg=$(date +%s%N)
-for arg in "$@"
-do
+# If launch script exists run it instead of pcsx/RA
+ls -l /data/AppData/sony/title/
+if [ -f "/data/AppData/sony/title/launch.sh" ]; then
+  echo "[INTERCEPT](INFO) launch.sh exists"
+  exec "/data/AppData/sony/title/launch.sh" 
+else
+  # Loop through each argument to pull out information relating to which game is being loaded
+  # and whether this is a Save State load
+  start_arg=$(date +%s%N)
+  for arg in "$@"; do
+    if [ "$found_cdfile" = true ]; then
+      intercept_game_path="$arg"
+      echo "[INTERCEPT](INFO) Game full path: ${intercept_game_path}"
+      intercept_game_dir="${arg%/*}/"
+      echo "[INTERCEPT](INFO) Game directory: ${intercept_game_dir}"
+      intercept_game_id="${arg##*/}"
+      intercept_game_id="${intercept_game_id%.*}"
+      echo "[INTERCEPT](INFO) Game ID: $intercept_game_id"
+      intercept_game_ext="${arg##*.}"
+      echo "[INTERCEPT](INFO) Game extension: $intercept_game_ext"
 
-  if [ "$found_cdfile" = true ]; then
+      # Check if the game exists in an alternative format
+      # The game path always has .cue appened to the BASENAME field of the DISC table in regional.db
+      # EXCEPT when the game is launched from a Save State. In this case the Game Path is determined from
+      # the first line of filename.txt.res in the games PCSX data directory (ie. /data/AppData/sony/pcsx/1/.pcsx/filename.txt.res)
+      if [ "$intercept_save_state" = false ]; then
 
-    intercept_game_path="$arg"
-    echo "[INTERCEPT](INFO) Game full path: ${intercept_game_path}"
-    intercept_game_dir="${arg%/*}/"
-    echo "[INTERCEPT](INFO) Game directory: ${intercept_game_dir}"
-    intercept_game_id="${arg##*/}"
-    intercept_game_id="${intercept_game_id%.*}"
-    echo "[INTERCEPT](INFO) Game ID: $intercept_game_id"
-    intercept_game_ext="${arg##*.}"
-    echo "[INTERCEPT](INFO) Game extension: $intercept_game_ext"
-
-    # Check if the game exists in an alternative format
-    # The game path always has .cue appened to the BASENAME field of the DISC table in regional.db
-    # EXCEPT when the game is launched from a Save State. In this case the Game Path is determined from
-    # the first line of filename.txt.res in the games PCSX data directory (ie. /data/AppData/sony/pcsx/1/.pcsx/filename.txt.res)
-    if [ "$intercept_save_state" = false ]; then
-
-      start_alt=$(date +%s%N)
-      for f in "${intercept_file_formats[@]}"; do
-        f_upper=$(echo $f | tr a-z A-Z)
-        if [ -f "${arg%.cue}.${f}" ]; then
-          intercept_game_alternative_path="${arg%.cue}.${f}"
-        elif [ -f "${arg%.cue}.${f_upper}" ]; then
-          intercept_game_alternative_path="${arg%.cue}.${f_upper}"
-          f=$f_upper
-        fi
-        if [ ! -z "$intercept_game_alternative_path" ]; then
-          echo "[INTERCEPT](INFO) Alternative game format exists (${f}), this will be used instead of the .cue"
-          arg="$intercept_game_alternative_path"
-          intercept_game_path="$arg"
-          intercept_game_ext="${f}"
-          echo "[INTERCEPT](INFO) New Game full path: ${intercept_game_path}"
-          echo "[INTERCEPT](INFO) New Game extension: ${intercept_game_ext}"
-          break
-        fi
-      done
-      end_alt=$(date +%s%N)
-      echo "[INTERCEPT](PROFILE) finding alternative game formats took: $(((end_alt-start_alt)/1000000))ms to execute"
+        start_alt=$(date +%s%N)
+        for f in "${intercept_file_formats[@]}"; do
+          f_upper=$(echo $f | tr a-z A-Z)
+          if [ -f "${arg%.cue}.${f}" ]; then
+            intercept_game_alternative_path="${arg%.cue}.${f}"
+          elif [ -f "${arg%.cue}.${f_upper}" ]; then
+            intercept_game_alternative_path="${arg%.cue}.${f_upper}"
+            f=$f_upper
+          fi
+          if [ ! -z "$intercept_game_alternative_path" ]; then
+            echo "[INTERCEPT](INFO) Alternative game format exists (${f}), this will be used instead of the .cue"
+            arg="$intercept_game_alternative_path"
+            intercept_game_path="$arg"
+            intercept_game_ext="${f}"
+            echo "[INTERCEPT](INFO) New Game full path: ${intercept_game_path}"
+            echo "[INTERCEPT](INFO) New Game extension: ${intercept_game_ext}"
+            break
+          fi
+        done
+        end_alt=$(date +%s%N)
+        echo "[INTERCEPT](PROFILE) finding alternative game formats took: $(((end_alt-start_alt)/1000000))ms to execute"
+      fi
+      found_cdfile=false
+      continue
     fi
-    found_cdfile=false
-    continue
+
+    case $arg in
+      -cdfile)
+        found_cdfile=true
+        continue
+        ;;
+
+      -load)
+        echo "[INTERCEPT](INFO) This is a Save State load"
+        intercept_save_state=true
+        ;;
+    esac
+
+    #   Build the new parameters for PCSX
+    intercept_command="${intercept_command} ${arg}"
+  done
+  end_arg=$(date +%s%N)
+  echo "[INTERCEPT](PROFILE) extracting arguments took: $(((end_arg-start_arg)/1000000))ms to execute"
+
+  if [ "$launch_ra_from_stock_UI" = "1" ]; then
+    echo "[INTERCEPT](INFO) RetroArch is enabled as the emulator"
+    # Swap stock multi disc game path to an .m3u for better disc swap support in RetroArch
+    case "$intercept_game_id" in
+      SCUS-94163|SLPM-86114|SLPS-01057|SLPS-01230|SLUS-00594)
+        if [ "$intercept_game_ext" = "cue" ] && [ "$intercept_save_state" = false ] ; then
+          echo "[INTERCEPT](INFO) This is a stock multi disc game with no .m3u. An .m3u is needed for the best multi disc experience within RetroArch"
+          if [ -f "$bleemsync_path/etc/bleemsync/SUP/retroarch/title/${intercept_game_id}.m3u" ]; then
+            intercept_game_path="$bleemsync_path/etc/bleemsync/SUP/retroarch/title/${intercept_game_id}.m3u"
+            intercept_game_ext="m3u"
+            echo "[INTERCEPT](INFO) New Game full path: ${intercept_game_path}"
+            echo "[INTERCEPT](INFO) New Game extension: ${intercept_game_ext}"
+          else
+            echo "[INTERCEPT](ERROR) an .m3u does not exist at $bleemsync_path/etc/bleemsync/SUP/retroarch/title/${intercept_game_id}.m3u"
+          fi 
+        fi
+        ;;
+    esac
+    end=$(date +%s%N)
+    echo "[INTERCEPT](PROFILE) up to launching RetroArch took: $(((end-start)/1000000))ms to execute"
+    echo -n 2 > /data/power/disable
+    link_ra_memory_cards
+    launch_retroarch_from_StockUI
+    exit_checkSaveState
+    resume_ui_menu
+    echo -n 1 > /data/power/disable
+    exit 0
   fi
 
-  case $arg in
-    -cdfile)
-      found_cdfile=true
-      continue
-      ;;
-
-     -load)
-      echo "[INTERCEPT](INFO) This is a Save State load"
-      intercept_save_state=true
-      ;;
-  esac
-
-  #   Build the new parameters for PCSX
-  intercept_command="${intercept_command} ${arg}"
-done
-end_arg=$(date +%s%N)
-echo "[INTERCEPT](PROFILE) extracting arguments took: $(((end_arg-start_arg)/1000000))ms to execute"
-
-
-if [ "$launch_ra_from_stock_UI" = "1" ]; then
-  echo "[INTERCEPT](INFO) RetroArch is enabled as the emulator"
-  # Swap stock multi disc game path to an .m3u for better disc swap support in RetroArch
-  case "$intercept_game_id" in
-    SCUS-94163|SLPM-86114|SLPS-01057|SLPS-01230|SLUS-00594)
-      if [ "$intercept_game_ext" = "cue" ] && [ "$intercept_save_state" = false ] ; then
-        echo "[INTERCEPT](INFO) This is a stock multi disc game with no .m3u. An .m3u is needed for the best multi disc experience within RetroArch"
-        if [ -f "$bleemsync_path/etc/bleemsync/SUP/retroarch/title/${intercept_game_id}.m3u" ]; then
-          intercept_game_path="$bleemsync_path/etc/bleemsync/SUP/retroarch/title/${intercept_game_id}.m3u"
-          intercept_game_ext="m3u"
-          echo "[INTERCEPT](INFO) New Game full path: ${intercept_game_path}"
-          echo "[INTERCEPT](INFO) New Game extension: ${intercept_game_ext}"
-        else
-          echo "[INTERCEPT](ERROR) an .m3u does not exist at $bleemsync_path/etc/bleemsync/SUP/retroarch/title/${intercept_game_id}.m3u"
-        fi 
-      fi
-      ;;
-  esac
+  echo "[INTERCEPT](INFO) Launching $intercept_pcsx_path $intercept_command -cdfile $intercept_game_path"
   end=$(date +%s%N)
-  echo "[INTERCEPT](PROFILE) up to launching RetroArch took: $(((end-start)/1000000))ms to execute"
-  echo -n 2 > /data/power/disable
-  link_ra_memory_cards
-  launch_retroarch_from_StockUI
-  exit_checkSaveState
+  echo "[INTERCEPT](PROFILE) up to launching stock pcsx took: $(((end-start)/1000000))ms to execute"
+  "$intercept_pcsx_path" $intercept_command -cdfile "$intercept_game_path"
   resume_ui_menu
-  echo -n 1 > /data/power/disable
-  exit 0
+  # Exit returning the pcsx exit code
+  exit $?
 fi
 
-echo "[INTERCEPT](INFO) Launching $intercept_pcsx_path $intercept_command -cdfile $intercept_game_path"
-end=$(date +%s%N)
-echo "[INTERCEPT](PROFILE) up to launching stock pcsx took: $(((end-start)/1000000))ms to execute"
-"$intercept_pcsx_path" $intercept_command -cdfile "$intercept_game_path"
-resume_ui_menu
-# Exit returning the pcsx exit code
-exit $?
